sudo: required
services:
  - docker

before_install:
  - docker build -t alanchu9222/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alanchu9222/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-west-2-123123123"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  